apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort # Um serviço em que o ip nunca muda, funciona com um clusterIp e permite a comunicação dom o mundo externo ao cluster 
  selector:
    app: primeiro-pod
  ports:
    - port: 80
      #targetPort: 80 se definir so o port implicitamente o kbernets assume que o targetport é igual
      nodePort: 30000 #Varia de 30000 -> 32767

#kubectl svc mostrais serviços -> CLUSTERIP -> IP Dentro do Cluster EXTERNAL-IP -> IP visto fora do cluster PORTS -> Portas atibuídas ao NodePort
# Para acessar pelo navegador, o windows implicitamente converte para localhost + porta presente em ExternalIP | Ports 
# O numero presente no PORTS é arbitrário, a não ser que o mesmo seja definido no arquivo de configuração

# No linux o processo é diferente:
# kubectl get nodes -o wide 
# usar o valor da campo INTERNAL-IP no navegador + a porta de acesso 
