apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306

#kubectl describe pods db-noticias ( consegue verificar tudo o que aconteceu no ciclo de vida do pod)